language: node_js
cache:
  directories:
    - node_modules
    - ~./npm
node_js:
  - '14'
git:
  depth: 3
script:
  - npm test
  - npm start
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 
  app: platzi-store-backend
  on:
    repo: angellovc/Simple.Book-Scrapper